# Copyright 2013 ChaiShushan <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default:
	msgfmt -o local/zh_CN/LC_MESSAGES/hello.mo local/zh_CN/LC_MESSAGES/hello.po
	msgfmt -o local/zh_TW/LC_MESSAGES/hello.mo local/zh_TW/LC_MESSAGES/hello.po
	go run hello.go
